module.exports = [
    {
      id: "sd_7lTfrt6Cf9D18M6X",
      type: "OnInit",
      z: "sd_3P2cK0EohtqlB3gG",
      viewType: "common",
      nodeType: "start",
      name: "",
      functionName: "sd_7lTfrt6Cf9D18M6X",
      category: "Lifecycle Events",
      x: 105,
      y: 120,
      wires: [["sd_9mrdYckLuTxBlVwN"]],
      __n_excludedFromValidation__: {},
    },
    {
      id: "sd_9mrdYckLuTxBlVwN",
      type: "Script",
      z: "sd_3P2cK0EohtqlB3gG",
      viewType: "common",
      nodeType: "flow",
      name: "",
      script:
        'bh.local.navbarValue = [{\n    "Link": "/ui/home",\n    "img":"https://res.cloudinary.com/ddtcmyvhx/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1684914273/Cart_uihrhu.jpg?_s=public-apps"\n\n},\n{\n    "Link": "/ui/profile",\n    "img":"https://res.cloudinary.com/ddtcmyvhx/image/upload/c_pad,b_auto:predominant,fl_preserve_transparency/v1684914273/Cart_uihrhu.jpg?_s=public-apps"\n\n}]',
      functionName: "sd_9mrdYckLuTxBlVwN",
      category: "Function",
      x: 245,
      y: 120,
      wires: [["sd_2lZeTT5zUUUj7P3O"]],
      __n_excludedFromValidation__: {},
    },
    {
      id: "sd_2lZeTT5zUUUj7P3O",
      type: "PageVariables",
      z: "sd_3P2cK0EohtqlB3gG",
      viewType: "pages",
      nodeType: "flow",
      name: "",
      inputs: 1,
      outputs: 1,
      operation: "set",
      globalVariables: [
        {
          textIp: "navBar",
          typedIpValue: {
            type: "bh.local",
            value: "navbarValue",
          },
        },
      ],
      functionName: "sd_2lZeTT5zUUUj7P3O",
      category: "Function",
      x: 425,
      y: 120,
      wires: [[]],
      __n_excludedFromValidation__: {},
    },
  ];
  