module.exports = [
  {
    id: "sd_zrAR33Ye7lx66Zgj",
    type: "OnInit",
    z: "sd_LIDAnDbHw9UbxkCR",
    viewType: "common",
    nodeType: "start",
    name: "",
    inputVariables: [],
    localVariables: [],
    outputVariables: [],
    pageVariables: [],
    functionName: "sd_zrAR33Ye7lx66Zgj",
    category: "Lifecycle Events",
    x: 45,
    y: 40,
    wires: [["sd_yGxv4THYziNBSaz7"]],
    __n_excludedFromValidation__: {},
  },
  {
    id: "sd_yGxv4THYziNBSaz7",
    type: "PageVariables",
    z: "sd_LIDAnDbHw9UbxkCR",
    viewType: "pages",
    nodeType: "flow",
    name: "",
    inputs: 1,
    outputs: 1,
    operation: "set",
    globalVariables: [],
    functionName: "sd_yGxv4THYziNBSaz7",
    category: "Function",
    x: 185,
    y: 60,
    wires: [["sd_OLogPnkIXIvbzjaW"]],
    __n_excludedFromValidation__: {},
  },
  {
    id: "sd_OLogPnkIXIvbzjaW",
    type: "PageCallService",
    z: "sd_LIDAnDbHw9UbxkCR",
    viewType: "pages",
    nodeType: "flow",
    name: "",
    outputs: 1,
    isValidNode: true,
    noerr: 0,
    service: {
      id: "sd_la6KIUXsIGgMIJgr",
      type: "tab",
      createdDate: "2023-05-01T17:52:38.714Z",
      label: "Scan",
      disabled: false,
      info: "",
      functionSeq: 0,
      tabType: "client",
    },
    flow: {
      flowId: "sd_FjImFQsv1VcX66QF",
      flowName: "scan",
    },
    inputVariables: [],
    outputMapping: [],
    serviceImportPath: "app/sd-services/Scan",
    startName: "scan",
    inputParams: [],
    accept_bh: false,
    accept_csd: true,
    functionName: "sd_OLogPnkIXIvbzjaW",
    category: "General",
    x: 325,
    y: 60,
    wires: [["sd_ZkmyuIakzgpuH7Kt"]],
    __n_excludedFromValidation__: {},
  },
  {
    id: "sd_Hw28PWA03NsPI3zR",
    type: "Script",
    z: "sd_LIDAnDbHw9UbxkCR",
    viewType: "common",
    nodeType: "flow",
    name: "tempscanscript",
    script:
      "// console.log(bh.local.scanner,\"bh.local.scanner\")\n\nbh.local.scanner.onUniqueRead = (txt, result) => {\n    console.log(txt)\n};\n\nawait bh.local.scanner.setUIElement((document.querySelector('.dce-video-container') as HTMLElement).parentElement as HTMLElement);\nawait bh.local.scanner.open();",
    functionName: "tempscanscript",
    category: "Function",
    x: 765,
    y: 60,
    wires: [[]],
    __n_excludedFromValidation__: {},
  },
  {
    id: "sd_ZkmyuIakzgpuH7Kt",
    type: "PageServiceVariables",
    z: "sd_LIDAnDbHw9UbxkCR",
    viewType: "pages",
    nodeType: "flow",
    name: "",
    inputs: 1,
    outputs: 1,
    operation: "get",
    globalVariables: [
      {
        textIp: "scanner",
        typedIpValue: {
          type: "bh.local",
          value: "scanner",
        },
      },
    ],
    functionName: "sd_ZkmyuIakzgpuH7Kt",
    service: {
      type: "tab",
      id: "sd_la6KIUXsIGgMIJgr",
      disabled: false,
      info: "",
      label: "Scan",
      createdDate: "2023-05-01T17:52:38.714Z",
      functionSeq: 0,
      tabType: "client",
      _def: {
        defaults: {
          label: {
            value: "",
          },
          disabled: {
            value: false,
          },
          info: {
            value: "",
          },
        },
      },
    },
    serviceImportPath: "app/sd-services/Scan",
    category: "Function",
    x: 525,
    y: 60,
    wires: [["sd_Hw28PWA03NsPI3zR"]],
    __n_excludedFromValidation__: {},
  },
  {
    id: "sd_8BKyQMXau1hrRhfl",
    type: "OnDestroy",
    z: "sd_LIDAnDbHw9UbxkCR",
    viewType: "common",
    nodeType: "start",
    name: "",
    functionName: "sd_8BKyQMXau1hrRhfl",
    category: "Lifecycle Events",
    x: 425,
    y: 140,
    wires: [["sd_lYWGr6AypaQgA5qs"]],
    __n_excludedFromValidation__: {},
  },
  {
    id: "sd_CQUQtKgQqR5cpSVV",
    type: "Script",
    z: "sd_LIDAnDbHw9UbxkCR",
    viewType: "common",
    nodeType: "flow",
    name: "",
    script:
      "\n// await bh.local.scanner.stopScanning();\n// await bh.local.scanner.stop();\nawait bh.local.scanner.close();\n// await bh.local.scanner.setUIElement(null);\n// await bh.local.scanner.destroyContext();\n// bh.local.scanner = null;",
    functionName: "sd_CQUQtKgQqR5cpSVV",
    category: "Function",
    x: 625,
    y: 140,
    wires: [[]],
    __n_excludedFromValidation__: {},
  },
  {
    id: "sd_lYWGr6AypaQgA5qs",
    type: "PageServiceVariables",
    z: "sd_LIDAnDbHw9UbxkCR",
    viewType: "pages",
    nodeType: "flow",
    name: "",
    inputs: 1,
    outputs: 1,
    operation: "get",
    globalVariables: [
      {
        textIp: "scanner",
        typedIpValue: {
          type: "bh.local",
          value: "scanner",
        },
      },
    ],
    functionName: "sd_lYWGr6AypaQgA5qs",
    service: {
      type: "tab",
      id: "sd_la6KIUXsIGgMIJgr",
      disabled: false,
      info: "",
      label: "Scan",
      createdDate: "2023-05-01T17:52:38.714Z",
      functionSeq: 0,
      tabType: "client",
      _def: {
        defaults: {
          label: {
            value: "",
          },
          disabled: {
            value: false,
          },
          info: {
            value: "",
          },
        },
      },
    },
    serviceImportPath: "app/sd-services/Scan",
    category: "Function",
    x: 525,
    y: 140,
    wires: [["sd_CQUQtKgQqR5cpSVV"]],
    __n_excludedFromValidation__: {},
  },
];
